#include <hwriter.h>
#include <logger.h>
#include <unistd.h>
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>

hwriter_t *hwriter_create(const char *output , const char *vn , const char *hg){	
	if(!vn || !hg){
		printl(fatal , "no variable name and header guard given.");
		return NULL;
	}
	if(!output){
		printl(warning , "no output filename given. using 'hpack.out'.");
		output = "hpack.out";
	}

	/* check file if the file exists and 
	 * also check its permission to write and read. */
	if(!access(output , F_OK)){ /* 0 means it exists. */
		printl(fatal , "%s exists in the filesystem , not instructed to overwrite." , output);
		return NULL;
	}

	printl(info , "started writing packed header file.");
	hwriter_t *d = calloc(1 , sizeof(hwriter_t));
	time_t current_time;
	struct tm * time_info;
	char time_string[9];
	time(&current_time);
	time_info = localtime(&current_time);
	strftime(time_string, sizeof(time_string), "%H:%M:%S", time_info);
	if(!d){
		printl(fatal , "not enough memory to allocate header writer.");
		return NULL;
	}

	/* open header file. */
	printl(info , "opening %s for writing." , output);
	if(!(d->fp = fopen(output , "w"))){
		printl(fatal , "cannot open %s for writing." , output);
		free(d);
		return NULL;
	}

	/* write boilerplate code with respect to the 
	 * given filename.*/
	printl(info , "using %s as the include guard." , hg);
	printl(info , "using %s as the variable name which the data will be assigned.",vn);
	
	fprintf(d->fp , "/*\n");
#ifdef GIT_VERSION_STR	
	fprintf(d->fp , " * Generated by hpack-%s.\n" , GIT_VERSION_STR);
#else 
	fprintf(d->fp , " * Generated by hpack.\n");
#endif
	fprintf(d->fp , " * Created on %s.\n" , time_string);
	fprintf(d->fp , "*/\n");
	fprintf(d->fp , "#ifndef %s_H_INCLUDED\n" , hg);
	fprintf(d->fp , "#define %s_H_INCLUDED\n" , hg);
	fprintf(d->fp , "const char %s[]={" , vn);
	printl(info , "finished writing boilerplate code.");
	return d;
}

void hwriter_destroy(hwriter_t *writer , const char *var_name){
	if(!writer)
		return;

	printl(info , "finalizing writing the header file.");	
	if(ftell(writer->fp) > 0){
		fseek(writer->fp , ftell(writer->fp) - 1 , SEEK_SET);
	}

	fprintf(writer->fp , "};\n");
	fprintf(writer->fp , "#define %s_filesize %d\n" , var_name,
			writer->bytes_received);	
	fprintf(writer->fp , "#endif");
	fclose(writer->fp);
	free(writer);
}

int hwriter_write_hex(hwriter_t *writer , const char *hex){
	if(!writer || !hex)
		return -1;
	fprintf(writer->fp , "%s," , hex);
	++(writer->bytes_received);
	return 0;
}
